[general]
google_api_key = "AIzaSyDfVrAN1Wn0OfGGYC7jqB9xhOoCqv4837U"
elevenlabs_api_key = "sk_c01c516d0962615b72a82086c5df7d0798436fde2e7f2d2b"
groq_api_key = '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'
